### ISSUE TITLE
Answer Hack doesnt work anymore

### ISSUE THREAD

**Issue by GooglyTank** [rxzyx/Duolingo-Hacks#11]
**Describe the bug**
When putting into console the error "uncaught" shows up

**To Reproduce**
1. Go to 'the console'
2. Click on 'the paste button'
3. Scroll down to 'All the errors'

**Expected behavior**
Expected to show me answers

**Screenshots**
No screenshots

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] idk

**Smartphone (please complete the following information):**

**Additional context**
I could just typed it out but github gave me this super usefull template anyways doesnt work u can test urself lol

**Comment by rxzyx** [comment]
False issue. Some features are not supported.
