### ISSUE TITLE
Plus Hack Not Working

### ISSUE THREAD

**Issue by phyouthcenter1** [rxzyx/Duolingo-Hacks#15]
**Describe the bug**
I went to duolingo.com/learn and put the script in the console and it said that I now have plus but it did not work.

**To Reproduce**
1. Go to duolingo.com/learn
2. Go to console
3. Paste in duolingo plus script
4. See problem

**Expected behavior**
I have plus and can review mistakes

**Video**

https://user-images.githubusercontent.com/67077196/214220320-0feabc1b-9d3d-44fb-b7cb-7841c687d754.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX
 - Version: Latest

**Comment by brennabre** [comment]
same mine dose not work either
