### ISSUE TITLE
Answer hack

### ISSUE THREAD

**Issue by Saber-Tooth-Tiger** [rxzyx/Duolingo-Hacks#5]
Hi there Ryzx, sry to bother again, but i dunno is it just me, but your answer hack does not work for skipping units :) I am a big fan of you :) I will continue to support you :) thanks 💯

**Comment by rxzyx** [comment]
Then the HTML element was changed, I’ll attempt to fix all my hacks within a time period of 2-3 days.

**Comment by rxzyx** [comment]
Thanks for waiting patiently and supporting.

**Comment by Saber-Tooth-Tiger** [comment]
Np, :)

**Comment by rxzyx** [comment]
Ok so I checked and all hacks work.

**Comment by rxzyx** [comment]
You're doing something wrong.

**Comment by Saber-Tooth-Tiger** [comment]
wait what? Okay, my steps are: Copy your script, create a bookmark, name
the book mark whatever i want and then type in the URL part:
javascript:whateverthecodeis

**Comment by rxzyx** [comment]
Try using dev console.

**Comment by Saber-Tooth-Tiger** [comment]
okay

**Comment by Saber-Tooth-Tiger** [comment]
so i just open console and paste in the code?

**Comment by rxzyx** [comment]
yes

**Comment by Saber-Tooth-Tiger** [comment]
okay lemme try

**Comment by Saber-Tooth-Tiger** [comment]
umm i tried still didn't work

**Comment by Saber-Tooth-Tiger** [comment]
it says, made by ryxyz, unlocked all skills then nothing happened

**Comment by Saber-Tooth-Tiger** [comment]
o i refresh the page?

**Comment by rxzyx** [comment]
u have to put ur mouse over the achievement/skill

**Comment by Saber-Tooth-Tiger** [comment]
ohhhhhhhhhh, so i click the skill that i wanna unlock right?

**Comment by rxzyx** [comment]
just hover ur mouse over it

**Comment by Saber-Tooth-Tiger** [comment]
still does not work, i tried it on the last unit of the french in duolingo,

**Comment by rxzyx** [comment]
weird, unlock all shouldn't need a hover. open the console, does it show an error?

**Comment by Saber-Tooth-Tiger** [comment]
yes it shows 4 red lines after each time i paste the console.

**Comment by rxzyx** [comment]
paste the messages here

**Comment by Saber-Tooth-Tiger** [comment]
Do you got like a video about it? :)

**Comment by rxzyx** [comment]
can't add images as a comment, paste the errors

**Comment by Saber-Tooth-Tiger** [comment]
3496-dc9c8736.js:2          GET
https://zombie.duolingo.com/54/web.json?user=935355054&ts=1664633487&tzoffset=-4
404
(anonymous) @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
e.exports @ 3496-dc9c8736.js:2
e.exports @ 3496-dc9c8736.js:2
Promise.then (async)
l.request @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
V @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
V @ app-33d1b155.js:1
request @ app-33d1b155.js:1
get @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Ie @ app-33d1b155.js:1
Pe @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Ie @ app-33d1b155.js:1
De @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
Be.s.current @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
setTimeout (async)
(anonymous) @ app-33d1b155.js:1
r @ app-33d1b155.js:1
Promise.then (async)
l @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Is @ 3496-dc9c8736.js:2
t.unstable_runWithPriority @ 3496-dc9c8736.js:2
qo @ 3496-dc9c8736.js:2
Cs @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
L @ 3496-dc9c8736.js:2
_.port1.onmessage @ 3496-dc9c8736.js:2
3496-dc9c8736.js:2          GET
https://brb.duolingo.com/54/web.json?user=935355054&ts=1664633487&tzoffset=-4
404
(anonymous) @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
e.exports @ 3496-dc9c8736.js:2
e.exports @ 3496-dc9c8736.js:2
Promise.then (async)
l.request @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
V @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
V @ app-33d1b155.js:1
request @ app-33d1b155.js:1
get @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Ie @ app-33d1b155.js:1
Pe @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Ie @ app-33d1b155.js:1
Re @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
Be.s.current @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
setTimeout (async)
(anonymous) @ app-33d1b155.js:1
r @ app-33d1b155.js:1
Promise.then (async)
l @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Is @ 3496-dc9c8736.js:2
t.unstable_runWithPriority @ 3496-dc9c8736.js:2
qo @ 3496-dc9c8736.js:2
Cs @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
L @ 3496-dc9c8736.js:2
_.port1.onmessage @ 3496-dc9c8736.js:2
3496-dc9c8736.js:2          GET
https://zombie.duolingo.com/54/web.json?user=935355054&ts=1664633527&tzoffset=-4
404
(anonymous) @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
e.exports @ 3496-dc9c8736.js:2
e.exports @ 3496-dc9c8736.js:2
Promise.then (async)
l.request @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
V @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
V @ app-33d1b155.js:1
request @ app-33d1b155.js:1
get @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Ie @ app-33d1b155.js:1
Pe @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Ie @ app-33d1b155.js:1
De @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
Be.s.current @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
setTimeout (async)
(anonymous) @ app-33d1b155.js:1
r @ app-33d1b155.js:1
Promise.then (async)
l @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
setTimeout (async)
(anonymous) @ app-33d1b155.js:1
r @ app-33d1b155.js:1
Promise.then (async)
l @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Is @ 3496-dc9c8736.js:2
t.unstable_runWithPriority @ 3496-dc9c8736.js:2
qo @ 3496-dc9c8736.js:2
Cs @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
L @ 3496-dc9c8736.js:2
_.port1.onmessage @ 3496-dc9c8736.js:2
3496-dc9c8736.js:2          GET
https://brb.duolingo.com/54/web.json?user=935355054&ts=1664633528&tzoffset=-4
404
(anonymous) @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
e.exports @ 3496-dc9c8736.js:2
e.exports @ 3496-dc9c8736.js:2
Promise.then (async)
l.request @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
V @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
V @ app-33d1b155.js:1
request @ app-33d1b155.js:1
get @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Ie @ app-33d1b155.js:1
Pe @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Ie @ app-33d1b155.js:1
Re @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
Be.s.current @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
setTimeout (async)
(anonymous) @ app-33d1b155.js:1
r @ app-33d1b155.js:1
Promise.then (async)
l @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
setTimeout (async)
(anonymous) @ app-33d1b155.js:1
r @ app-33d1b155.js:1
Promise.then (async)
l @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Is @ 3496-dc9c8736.js:2
t.unstable_runWithPriority @ 3496-dc9c8736.js:2
qo @ 3496-dc9c8736.js:2
Cs @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
L @ 3496-dc9c8736.js:2
_.port1.onmessage @ 3496-dc9c8736.js:2
3496-dc9c8736.js:2          GET
https://zombie.duolingo.com/54/web.json?user=935355054&ts=1664633573&tzoffset=-4
404
(anonymous) @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
e.exports @ 3496-dc9c8736.js:2
e.exports @ 3496-dc9c8736.js:2
Promise.then (async)
l.request @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
V @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
V @ app-33d1b155.js:1
request @ app-33d1b155.js:1
get @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Ie @ app-33d1b155.js:1
Pe @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Ie @ app-33d1b155.js:1
De @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
Be.s.current @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
setTimeout (async)
(anonymous) @ app-33d1b155.js:1
r @ app-33d1b155.js:1
Promise.then (async)
l @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
setTimeout (async)
(anonymous) @ app-33d1b155.js:1
r @ app-33d1b155.js:1
Promise.then (async)
l @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
setTimeout (async)
(anonymous) @ app-33d1b155.js:1
r @ app-33d1b155.js:1
Promise.then (async)
l @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Is @ 3496-dc9c8736.js:2
t.unstable_runWithPriority @ 3496-dc9c8736.js:2
qo @ 3496-dc9c8736.js:2
Cs @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
L @ 3496-dc9c8736.js:2
_.port1.onmessage @ 3496-dc9c8736.js:2
3496-dc9c8736.js:2          GET
https://brb.duolingo.com/54/web.json?user=935355054&ts=1664633576&tzoffset=-4
404
(anonymous) @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
e.exports @ 3496-dc9c8736.js:2
e.exports @ 3496-dc9c8736.js:2
Promise.then (async)
l.request @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
V @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
V @ app-33d1b155.js:1
request @ app-33d1b155.js:1
get @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Ie @ app-33d1b155.js:1
Pe @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Ie @ app-33d1b155.js:1
Re @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
Be.s.current @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
setTimeout (async)
(anonymous) @ app-33d1b155.js:1
r @ app-33d1b155.js:1
Promise.then (async)
l @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
setTimeout (async)
(anonymous) @ app-33d1b155.js:1
r @ app-33d1b155.js:1
Promise.then (async)
l @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
setTimeout (async)
(anonymous) @ app-33d1b155.js:1
r @ app-33d1b155.js:1
Promise.then (async)
l @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Fe @ app-33d1b155.js:1
t @ app-33d1b155.js:1
(anonymous) @ app-33d1b155.js:1
Is @ 3496-dc9c8736.js:2
t.unstable_runWithPriority @ 3496-dc9c8736.js:2
qo @ 3496-dc9c8736.js:2
Cs @ 3496-dc9c8736.js:2
(anonymous) @ 3496-dc9c8736.js:2
L @ 3496-dc9c8736.js:2
_.port1.onmessage @ 3496-dc9c8736.js:2
3496-dc9c8736.js:2          GET
https://zombie.duolingo.com/54/web.json?user=935355054&ts=1664633605&tzoffset=-4
404

**Comment by rxzyx** [comment]
so ur at the "learn" area and it didn't unlock anything?

**Comment by Saber-Tooth-Tiger** [comment]
[image: image.png]

**Comment by rxzyx** [comment]
not related error, means code works

**Comment by Saber-Tooth-Tiger** [comment]
yes, here a picture of it: [image: image.png]

**Comment by Saber-Tooth-Tiger** [comment]
then whats wrong with it?

**Comment by Saber-Tooth-Tiger** [comment]
so weird :(

**Comment by rxzyx** [comment]
idek. Also I can't see the image.

**Comment by Saber-Tooth-Tiger** [comment]
That's weird. why can't you? oh i kow, because of my schoolboard, can we
email or chat on my private account?
its: ***@***.***

**Comment by rxzyx** [comment]
u have disc?

**Comment by Saber-Tooth-Tiger** [comment]
my discord is
Player Unknown#2501

**Comment by Saber-Tooth-Tiger** [comment]
Yeah, I do.
