### ISSUE TITLE
Max all skills does not work

### ISSUE THREAD

**Issue by ASTHEBEST** [rxzyx/Duolingo-Hacks#7]
**Describe the bug**
The max all skill hack does not work

**To Reproduce**
1. Use the hack
2. Reload the page
3. It gets reset

**Expected behavior**
It was still supposed to be maxed

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser: Chrome
 - Version: 106.0.5249.103 (Official Build)

**FIX IT PLEASE**

**Comment by ASTHEBEST** [comment]
same with unlock all skills

**Comment by rxzyx** [comment]
Some countries have different UI.

**Comment by rxzyx** [comment]
It's not supposed to stay.

**Comment by rxzyx** [comment]
It's client-side. False issue.

**Comment by ASTHEBEST** [comment]
wait answer hack does not work too. It says 1497VM850:1 Uncaught TypeError: Cannot read properties of null (reading 'children')
    at <anonymous>:1:26851

**Comment by rxzyx** [comment]
that means u have a different UI change, some countries have a different UI.
